name: build

on:  # cf. https://github.community/t/how-to-trigger-an-action-on-push-or-pull-request-but-not-both/16662
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:
    name: Lint, test & build PDF
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Spell Check Repo ✍️
        uses: crate-ci/typos@3be83342e28b9421997e9f781f713f8dde8453d2 # v1.31.2
      - name: Set up Python 3.8
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          pip install -r requirements.txt -r extra-requirements.txt
          git clone https://github.com/clintbellanger/heroine-dusk
      - name: Linter
        run: pylint pdf_game/ gen_pdf.py hall_of_fame/hof_app.py trailer/*.py
      - name: Tests
        run: pytest pdf_game/ -vv --showlocals
      - name: Checking that all images use the DawnBringer palette
        run: ./check_dawnbringer.py $(git ls-files | grep .png | grep -v yellow-star.png)
      - name: Build PDF
        env:
          NO_TQDM: 1
          PYTHONUNBUFFERED: 1
        run: ./gen_pdf.py
      - name: Build trailer GIFs
        env:
          PYTHONPATH: .
        run: trailer/gen_promo_images.py
